name: dev-flowrank
services:
  frontend:
    container_name: front
    build:
      context: ./front
      target: development
    restart: unless-stopped
    volumes:
      - ./front:/front
      - /front/node_modules/
    ports:
      - 5173:5173

  backend:
    container_name: back
    build:
      context: ./back
      dockerfile: Dockerfile
      target: development
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./back:/back

  postgres:
    container_name: db
    image: postgres:17-alpine
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database:
