name: prod-flowrank
services:
  # frontend:
  #   # image:
  #   build:
  #     context: ./front
  #     target: development
  #   restart : unless-stopped
  #   volumes:
  #     - ./front:/front
  #     - ./front/node_modules/
  #   ports:
  #     - 5173:5173

  backend:
    # image:
    build:
      context: ./back
      target: production
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./back:/back

  postgres:
    image: postgres:17-alpine
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database:
