name: dev-flowrank
services:
  frontend:
    # image:
    build:
      context: ./front
      target: development
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./front:/front
      - /front/node_modules/
    ports:
      - 5173:5173

  backend:
    # image:
    build:
      context: ./back
      dockerfile: Dockerfile
      target: development
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./back:/app/back

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/healthcheck"]
      start_period: 30s
      interval: 30s
      timeout: 5s
      retries: 3
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 5002:5000

  postgres:
    image: postgres:17-alpine
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      start_period: 10s
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database:
